package main

import (
	"log"
	"net/http"
	"os"

	"github.com/gin-gonic/gin"
	"github.com/golang-jwt/jwt/v4"
)

type Config struct {
	Port      string `json:"port" env:"PORT" default:"8080"`
	JWTSecret string `json:"jwt_secret" env:"JWT_SECRET"`
	RedisURL  string `json:"redis_url" env:"REDIS_URL"`
}

type Server struct {
	config *Config
	router *gin.Engine
}

func NewServer(config *Config) *Server {
	gin.SetMode(gin.ReleaseMode)
	server := &Server{
		config: config,
		router: gin.New(),
	}

	server.setupRoutes()
	return server
}

func (s *Server) setupRoutes() {
	s.router.Use(gin.Logger())
	s.router.Use(gin.Recovery())

	// CORS middleware
	s.router.Use(func(c *gin.Context) {
		c.Header("Access-Control-Allow-Origin", "*")
		c.Header("Access-Control-Allow-Methods", "GET, POST, PUT, DELETE, OPTIONS")
		c.Header("Access-Control-Allow-Headers", "Origin, Content-Type, Authorization")

		if c.Request.Method == "OPTIONS" {
			c.AbortWithStatus(http.StatusNoContent)
			return
		}

		c.Next()
	})

	// Health check
	s.router.GET("/health", s.healthCheck)

	// API v1 routes
	v1 := s.router.Group("/api/v1")
	{
				v1.GET("/frameworkconfigs", s.ListFrameworkConfig)
		v1.POST("/frameworkconfigs", s.CreateFrameworkConfig)
		v1.GET("/frameworkconfigs/{id}", s.GetFrameworkConfig)
		v1.PUT("/frameworkconfigs/{id}", s.UpdateFrameworkConfig)
		v1.DELETE("/frameworkconfigs/{id}", s.DeleteFrameworkConfig)
		v1.GET("/corsconfigs", s.ListCORSConfig)
		v1.POST("/corsconfigs", s.CreateCORSConfig)
		v1.GET("/corsconfigs/{id}", s.GetCORSConfig)
		v1.PUT("/corsconfigs/{id}", s.UpdateCORSConfig)
		v1.DELETE("/corsconfigs/{id}", s.DeleteCORSConfig)
		v1.GET("/databaseconfigs", s.ListDatabaseConfig)
		v1.POST("/databaseconfigs", s.CreateDatabaseConfig)
		v1.GET("/databaseconfigs/{id}", s.GetDatabaseConfig)
		v1.PUT("/databaseconfigs/{id}", s.UpdateDatabaseConfig)
		v1.DELETE("/databaseconfigs/{id}", s.DeleteDatabaseConfig)
		v1.GET("/documentationconfigs", s.ListDocumentationConfig)
		v1.POST("/documentationconfigs", s.CreateDocumentationConfig)
		v1.GET("/documentationconfigs/{id}", s.GetDocumentationConfig)
		v1.PUT("/documentationconfigs/{id}", s.UpdateDocumentationConfig)
		v1.DELETE("/documentationconfigs/{id}", s.DeleteDocumentationConfig)
		v1.GET("/testingconfigs", s.ListTestingConfig)
		v1.POST("/testingconfigs", s.CreateTestingConfig)
		v1.GET("/testingconfigs/{id}", s.GetTestingConfig)
		v1.PUT("/testingconfigs/{id}", s.UpdateTestingConfig)
		v1.DELETE("/testingconfigs/{id}", s.DeleteTestingConfig)
		v1.GET("/deploymentconfigs", s.ListDeploymentConfig)
		v1.POST("/deploymentconfigs", s.CreateDeploymentConfig)
		v1.GET("/deploymentconfigs/{id}", s.GetDeploymentConfig)
		v1.PUT("/deploymentconfigs/{id}", s.UpdateDeploymentConfig)
		v1.DELETE("/deploymentconfigs/{id}", s.DeleteDeploymentConfig)
		v1.GET("/frameworkregistrys/{id}", s.GetGenerator)
		v1.GET("/frameworkregistrys", s.ListFrameworks)
		v1.GET("/frameworkregistrys", s.ListFrameworkRegistry)
		v1.POST("/frameworkregistrys", s.CreateFrameworkRegistry)
		v1.GET("/frameworkregistrys/{id}", s.GetFrameworkRegistry)
		v1.PUT("/frameworkregistrys/{id}", s.UpdateFrameworkRegistry)
		v1.DELETE("/frameworkregistrys/{id}", s.DeleteFrameworkRegistry)
		v1.GET("/gingenerators/{id}", s.GetName)
		v1.GET("/gingenerators/{id}", s.GetType)
		v1.GET("/gingenerators/{id}", s.GetDefaultConfig)
		v1.GET("/gingenerators", s.ListGinGenerator)
		v1.POST("/gingenerators", s.CreateGinGenerator)
		v1.GET("/gingenerators/{id}", s.GetGinGenerator)
		v1.PUT("/gingenerators/{id}", s.UpdateGinGenerator)
		v1.DELETE("/gingenerators/{id}", s.DeleteGinGenerator)
		v1.GET("/echogenerators/{id}", s.GetName)
		v1.GET("/echogenerators/{id}", s.GetType)
		v1.GET("/echogenerators/{id}", s.GetDefaultConfig)
		v1.GET("/echogenerators", s.ListEchoGenerator)
		v1.POST("/echogenerators", s.CreateEchoGenerator)
		v1.GET("/echogenerators/{id}", s.GetEchoGenerator)
		v1.PUT("/echogenerators/{id}", s.UpdateEchoGenerator)
		v1.DELETE("/echogenerators/{id}", s.DeleteEchoGenerator)
		v1.GET("/chigenerators/{id}", s.GetName)
		v1.GET("/chigenerators/{id}", s.GetType)
		v1.GET("/chigenerators/{id}", s.GetDefaultConfig)
		v1.GET("/chigenerators", s.ListChiGenerator)
		v1.POST("/chigenerators", s.CreateChiGenerator)
		v1.GET("/chigenerators/{id}", s.GetChiGenerator)
		v1.PUT("/chigenerators/{id}", s.UpdateChiGenerator)
		v1.DELETE("/chigenerators/{id}", s.DeleteChiGenerator)
		v1.GET("/fibergenerators/{id}", s.GetName)
		v1.GET("/fibergenerators/{id}", s.GetType)
		v1.GET("/fibergenerators/{id}", s.GetDefaultConfig)
		v1.GET("/fibergenerators", s.ListFiberGenerator)
		v1.POST("/fibergenerators", s.CreateFiberGenerator)
		v1.GET("/fibergenerators/{id}", s.GetFiberGenerator)
		v1.PUT("/fibergenerators/{id}", s.UpdateFiberGenerator)
		v1.DELETE("/fibergenerators/{id}", s.DeleteFiberGenerator)
		v1.GET("/packageinfos", s.ListPackageInfo)
		v1.POST("/packageinfos", s.CreatePackageInfo)
		v1.GET("/packageinfos/{id}", s.GetPackageInfo)
		v1.PUT("/packageinfos/{id}", s.UpdatePackageInfo)
		v1.DELETE("/packageinfos/{id}", s.DeletePackageInfo)
		v1.GET("/structinfos", s.ListStructInfo)
		v1.POST("/structinfos", s.CreateStructInfo)
		v1.GET("/structinfos/{id}", s.GetStructInfo)
		v1.PUT("/structinfos/{id}", s.UpdateStructInfo)
		v1.DELETE("/structinfos/{id}", s.DeleteStructInfo)
		v1.GET("/fieldinfos", s.ListFieldInfo)
		v1.POST("/fieldinfos", s.CreateFieldInfo)
		v1.GET("/fieldinfos/{id}", s.GetFieldInfo)
		v1.PUT("/fieldinfos/{id}", s.UpdateFieldInfo)
		v1.DELETE("/fieldinfos/{id}", s.DeleteFieldInfo)
		v1.GET("/methodinfos", s.ListMethodInfo)
		v1.POST("/methodinfos", s.CreateMethodInfo)
		v1.GET("/methodinfos/{id}", s.GetMethodInfo)
		v1.PUT("/methodinfos/{id}", s.UpdateMethodInfo)
		v1.DELETE("/methodinfos/{id}", s.DeleteMethodInfo)
		v1.GET("/parameters", s.ListParameter)
		v1.POST("/parameters", s.CreateParameter)
		v1.GET("/parameters/{id}", s.GetParameter)
		v1.PUT("/parameters/{id}", s.UpdateParameter)
		v1.DELETE("/parameters/{id}", s.DeleteParameter)
		v1.GET("/taginfos", s.ListTagInfo)
		v1.POST("/taginfos", s.CreateTagInfo)
		v1.GET("/taginfos/{id}", s.GetTagInfo)
		v1.PUT("/taginfos/{id}", s.UpdateTagInfo)
		v1.DELETE("/taginfos/{id}", s.DeleteTagInfo)
		v1.GET("/annotations", s.ListAnnotation)
		v1.POST("/annotations", s.CreateAnnotation)
		v1.GET("/annotations/{id}", s.GetAnnotation)
		v1.PUT("/annotations/{id}", s.UpdateAnnotation)
		v1.DELETE("/annotations/{id}", s.DeleteAnnotation)
		v1.GET("/apigenerators/{id}", s.getTypeString)
		v1.GET("/apigenerators/{id}", s.getCommentText)
		v1.GET("/apigenerators/{id}", s.getTypeString)
		v1.GET("/apigenerators/{id}", s.getCommentText)
		v1.GET("/apigenerators", s.ListAPIGenerator)
		v1.POST("/apigenerators", s.CreateAPIGenerator)
		v1.GET("/apigenerators/{id}", s.GetAPIGenerator)
		v1.PUT("/apigenerators/{id}", s.UpdateAPIGenerator)
		v1.DELETE("/apigenerators/{id}", s.DeleteAPIGenerator)
		v1.GET("/generatorconfigs", s.ListGeneratorConfig)
		v1.POST("/generatorconfigs", s.CreateGeneratorConfig)
		v1.GET("/generatorconfigs/{id}", s.GetGeneratorConfig)
		v1.PUT("/generatorconfigs/{id}", s.UpdateGeneratorConfig)
		v1.DELETE("/generatorconfigs/{id}", s.DeleteGeneratorConfig)
		v1.GET("/apiroutes", s.ListAPIRoute)
		v1.POST("/apiroutes", s.CreateAPIRoute)
		v1.GET("/apiroutes/{id}", s.GetAPIRoute)
		v1.PUT("/apiroutes/{id}", s.UpdateAPIRoute)
		v1.DELETE("/apiroutes/{id}", s.DeleteAPIRoute)
		v1.GET("/authconfigs", s.ListAuthConfig)
		v1.POST("/authconfigs", s.CreateAuthConfig)
		v1.GET("/authconfigs/{id}", s.GetAuthConfig)
		v1.PUT("/authconfigs/{id}", s.UpdateAuthConfig)
		v1.DELETE("/authconfigs/{id}", s.DeleteAuthConfig)
		v1.GET("/jwtconfigs", s.ListJWTConfig)
		v1.POST("/jwtconfigs", s.CreateJWTConfig)
		v1.GET("/jwtconfigs/{id}", s.GetJWTConfig)
		v1.PUT("/jwtconfigs/{id}", s.UpdateJWTConfig)
		v1.DELETE("/jwtconfigs/{id}", s.DeleteJWTConfig)
		v1.GET("/methodmappings", s.ListMethodMapping)
		v1.POST("/methodmappings", s.CreateMethodMapping)
		v1.GET("/methodmappings/{id}", s.GetMethodMapping)
		v1.PUT("/methodmappings/{id}", s.UpdateMethodMapping)
		v1.DELETE("/methodmappings/{id}", s.DeleteMethodMapping)
		v1.GET("/plugincontexts", s.ListPluginContext)
		v1.POST("/plugincontexts", s.CreatePluginContext)
		v1.GET("/plugincontexts/{id}", s.GetPluginContext)
		v1.PUT("/plugincontexts/{id}", s.UpdatePluginContext)
		v1.DELETE("/plugincontexts/{id}", s.DeletePluginContext)
		v1.GET("/plugindependencys", s.ListPluginDependency)
		v1.POST("/plugindependencys", s.CreatePluginDependency)
		v1.GET("/plugindependencys/{id}", s.GetPluginDependency)
		v1.PUT("/plugindependencys/{id}", s.UpdatePluginDependency)
		v1.DELETE("/plugindependencys/{id}", s.DeletePluginDependency)
		v1.GET("/pluginconfigs", s.ListPluginConfig)
		v1.POST("/pluginconfigs", s.CreatePluginConfig)
		v1.GET("/pluginconfigs/{id}", s.GetPluginConfig)
		v1.PUT("/pluginconfigs/{id}", s.UpdatePluginConfig)
		v1.DELETE("/pluginconfigs/{id}", s.DeletePluginConfig)
		v1.GET("/pluginmanagers/{id}/exists", s.checkDependencies)
		v1.PUT("/pluginmanagers/{id}/activate", s.EnablePlugin)
		v1.PUT("/pluginmanagers/{id}/deactivate", s.DisablePlugin)
		v1.GET("/pluginmanagers/{id}", s.GetPlugin)
		v1.GET("/pluginmanagers", s.ListPlugins)
		v1.GET("/pluginmanagers/{id}/exists", s.checkDependencies)
		v1.PUT("/pluginmanagers/{id}/activate", s.EnablePlugin)
		v1.PUT("/pluginmanagers/{id}/deactivate", s.DisablePlugin)
		v1.GET("/pluginmanagers/{id}", s.GetPlugin)
		v1.GET("/pluginmanagers", s.ListPlugins)
		v1.GET("/pluginmanagers", s.ListPluginManager)
		v1.POST("/pluginmanagers", s.CreatePluginManager)
		v1.GET("/pluginmanagers/{id}", s.GetPluginManager)
		v1.PUT("/pluginmanagers/{id}", s.UpdatePluginManager)
		v1.DELETE("/pluginmanagers/{id}", s.DeletePluginManager)
		v1.GET("/pluginmanagerconfigs", s.ListPluginManagerConfig)
		v1.POST("/pluginmanagerconfigs", s.CreatePluginManagerConfig)
		v1.GET("/pluginmanagerconfigs/{id}", s.GetPluginManagerConfig)
		v1.PUT("/pluginmanagerconfigs/{id}", s.UpdatePluginManagerConfig)
		v1.DELETE("/pluginmanagerconfigs/{id}", s.DeletePluginManagerConfig)
		v1.GET("/pluginmetadatas", s.ListPluginMetadata)
		v1.POST("/pluginmetadatas", s.CreatePluginMetadata)
		v1.GET("/pluginmetadatas/{id}", s.GetPluginMetadata)
		v1.PUT("/pluginmetadatas/{id}", s.UpdatePluginMetadata)
		v1.DELETE("/pluginmetadatas/{id}", s.DeletePluginMetadata)
		v1.GET("/plugininfos", s.ListpluginInfo)
		v1.POST("/plugininfos", s.CreatepluginInfo)
		v1.GET("/plugininfos/{id}", s.GetpluginInfo)
		v1.PUT("/plugininfos/{id}", s.UpdatepluginInfo)
		v1.DELETE("/plugininfos/{id}", s.DeletepluginInfo)
		v1.GET("/loggingplugins/{id}", s.GetName)
		v1.GET("/loggingplugins/{id}", s.GetVersion)
		v1.GET("/loggingplugins/{id}", s.GetDescription)
		v1.GET("/loggingplugins/{id}", s.GetAuthor)
		v1.GET("/loggingplugins/{id}", s.GetSupportedFrameworks)
		v1.GET("/loggingplugins/{id}", s.GetSupportedEvents)
		v1.GET("/loggingplugins/{id}", s.GetDependencies)
		v1.GET("/loggingplugins/{id}", s.GetConfigSchema)
		v1.GET("/loggingplugins/{id}", s.GetName)
		v1.GET("/loggingplugins/{id}", s.GetVersion)
		v1.GET("/loggingplugins/{id}", s.GetDescription)
		v1.GET("/loggingplugins/{id}", s.GetAuthor)
		v1.GET("/loggingplugins/{id}", s.GetSupportedFrameworks)
		v1.GET("/loggingplugins/{id}", s.GetSupportedEvents)
		v1.GET("/loggingplugins/{id}", s.GetDependencies)
		v1.GET("/loggingplugins/{id}", s.GetConfigSchema)
		v1.GET("/loggingplugins", s.ListLoggingPlugin)
		v1.POST("/loggingplugins", s.CreateLoggingPlugin)
		v1.GET("/loggingplugins/{id}", s.GetLoggingPlugin)
		v1.PUT("/loggingplugins/{id}", s.UpdateLoggingPlugin)
		v1.DELETE("/loggingplugins/{id}", s.DeleteLoggingPlugin)
		v1.GET("/metricsplugins/{id}", s.GetName)
		v1.GET("/metricsplugins/{id}", s.GetVersion)
		v1.GET("/metricsplugins/{id}", s.GetDescription)
		v1.GET("/metricsplugins/{id}", s.GetAuthor)
		v1.GET("/metricsplugins/{id}", s.GetSupportedFrameworks)
		v1.GET("/metricsplugins/{id}", s.GetSupportedEvents)
		v1.GET("/metricsplugins/{id}", s.GetDependencies)
		v1.GET("/metricsplugins/{id}", s.GetConfigSchema)
		v1.GET("/metricsplugins/{id}", s.GetName)
		v1.GET("/metricsplugins/{id}", s.GetVersion)
		v1.GET("/metricsplugins/{id}", s.GetDescription)
		v1.GET("/metricsplugins/{id}", s.GetAuthor)
		v1.GET("/metricsplugins/{id}", s.GetSupportedFrameworks)
		v1.GET("/metricsplugins/{id}", s.GetSupportedEvents)
		v1.GET("/metricsplugins/{id}", s.GetDependencies)
		v1.GET("/metricsplugins/{id}", s.GetConfigSchema)
		v1.GET("/metricsplugins", s.ListMetricsPlugin)
		v1.POST("/metricsplugins", s.CreateMetricsPlugin)
		v1.GET("/metricsplugins/{id}", s.GetMetricsPlugin)
		v1.PUT("/metricsplugins/{id}", s.UpdateMetricsPlugin)
		v1.DELETE("/metricsplugins/{id}", s.DeleteMetricsPlugin)
		v1.GET("/testsuites", s.ListTestSuite)
		v1.POST("/testsuites", s.CreateTestSuite)
		v1.GET("/testsuites/{id}", s.GetTestSuite)
		v1.PUT("/testsuites/{id}", s.UpdateTestSuite)
		v1.DELETE("/testsuites/{id}", s.DeleteTestSuite)
		v1.GET("/mockvalidators/{id}", s.GetName)
		v1.GET("/mockvalidators/{id}", s.GetType)
		v1.GET("/mockvalidators/{id}", s.GetName)
		v1.GET("/mockvalidators/{id}", s.GetType)
		v1.GET("/mockvalidators", s.ListMockValidator)
		v1.POST("/mockvalidators", s.CreateMockValidator)
		v1.GET("/mockvalidators/{id}", s.GetMockValidator)
		v1.PUT("/mockvalidators/{id}", s.UpdateMockValidator)
		v1.DELETE("/mockvalidators/{id}", s.DeleteMockValidator)
		v1.GET("/mockplugins/{id}", s.GetName)
		v1.GET("/mockplugins/{id}", s.GetVersion)
		v1.GET("/mockplugins/{id}", s.GetDescription)
		v1.GET("/mockplugins/{id}", s.GetAuthor)
		v1.GET("/mockplugins/{id}", s.GetSupportedFrameworks)
		v1.GET("/mockplugins/{id}", s.GetSupportedEvents)
		v1.GET("/mockplugins/{id}", s.GetDependencies)
		v1.GET("/mockplugins/{id}", s.GetConfigSchema)
		v1.GET("/mockplugins/{id}", s.GetName)
		v1.GET("/mockplugins/{id}", s.GetVersion)
		v1.GET("/mockplugins/{id}", s.GetDescription)
		v1.GET("/mockplugins/{id}", s.GetAuthor)
		v1.GET("/mockplugins/{id}", s.GetSupportedFrameworks)
		v1.GET("/mockplugins/{id}", s.GetSupportedEvents)
		v1.GET("/mockplugins/{id}", s.GetDependencies)
		v1.GET("/mockplugins/{id}", s.GetConfigSchema)
		v1.GET("/mockplugins", s.ListMockPlugin)
		v1.POST("/mockplugins", s.CreateMockPlugin)
		v1.GET("/mockplugins/{id}", s.GetMockPlugin)
		v1.PUT("/mockplugins/{id}", s.UpdateMockPlugin)
		v1.DELETE("/mockplugins/{id}", s.DeleteMockPlugin)
		v1.GET("/performancemetricss", s.ListPerformanceMetrics)
		v1.POST("/performancemetricss", s.CreatePerformanceMetrics)
		v1.GET("/performancemetricss/{id}", s.GetPerformanceMetrics)
		v1.PUT("/performancemetricss/{id}", s.UpdatePerformanceMetrics)
		v1.DELETE("/performancemetricss/{id}", s.DeletePerformanceMetrics)
		v1.GET("/validationrules", s.ListValidationRule)
		v1.POST("/validationrules", s.CreateValidationRule)
		v1.GET("/validationrules/{id}", s.GetValidationRule)
		v1.PUT("/validationrules/{id}", s.UpdateValidationRule)
		v1.DELETE("/validationrules/{id}", s.DeleteValidationRule)
		v1.GET("/validationresults", s.ListValidationResult)
		v1.POST("/validationresults", s.CreateValidationResult)
		v1.GET("/validationresults/{id}", s.GetValidationResult)
		v1.PUT("/validationresults/{id}", s.UpdateValidationResult)
		v1.DELETE("/validationresults/{id}", s.DeleteValidationResult)
		v1.GET("/validationerrors", s.ListValidationError)
		v1.POST("/validationerrors", s.CreateValidationError)
		v1.GET("/validationerrors/{id}", s.GetValidationError)
		v1.PUT("/validationerrors/{id}", s.UpdateValidationError)
		v1.DELETE("/validationerrors/{id}", s.DeleteValidationError)
		v1.POST("/validationengines", s.AddRule)
		v1.GET("/validationengines/{id}", s.GetRulesForFramework)
		v1.POST("/validationengines", s.AddRule)
		v1.GET("/validationengines/{id}", s.GetRulesForFramework)
		v1.GET("/validationengines", s.ListValidationEngine)
		v1.POST("/validationengines", s.CreateValidationEngine)
		v1.GET("/validationengines/{id}", s.GetValidationEngine)
		v1.PUT("/validationengines/{id}", s.UpdateValidationEngine)
		v1.DELETE("/validationengines/{id}", s.DeleteValidationEngine)
		v1.GET("/validationconfigs", s.ListValidationConfig)
		v1.POST("/validationconfigs", s.CreateValidationConfig)
		v1.GET("/validationconfigs/{id}", s.GetValidationConfig)
		v1.PUT("/validationconfigs/{id}", s.UpdateValidationConfig)
		v1.DELETE("/validationconfigs/{id}", s.DeleteValidationConfig)
		v1.GET("/requiredvalidators/{id}", s.GetName)
		v1.GET("/requiredvalidators/{id}", s.GetType)
		v1.GET("/requiredvalidators/{id}", s.GetName)
		v1.GET("/requiredvalidators/{id}", s.GetType)
		v1.GET("/requiredvalidators", s.ListRequiredValidator)
		v1.POST("/requiredvalidators", s.CreateRequiredValidator)
		v1.GET("/requiredvalidators/{id}", s.GetRequiredValidator)
		v1.PUT("/requiredvalidators/{id}", s.UpdateRequiredValidator)
		v1.DELETE("/requiredvalidators/{id}", s.DeleteRequiredValidator)
		v1.GET("/stringvalidators/{id}", s.GetName)
		v1.GET("/stringvalidators/{id}", s.GetType)
		v1.GET("/stringvalidators/{id}", s.GetName)
		v1.GET("/stringvalidators/{id}", s.GetType)
		v1.GET("/stringvalidators", s.ListStringValidator)
		v1.POST("/stringvalidators", s.CreateStringValidator)
		v1.GET("/stringvalidators/{id}", s.GetStringValidator)
		v1.PUT("/stringvalidators/{id}", s.UpdateStringValidator)
		v1.DELETE("/stringvalidators/{id}", s.DeleteStringValidator)
		v1.GET("/emailvalidators/{id}", s.GetName)
		v1.GET("/emailvalidators/{id}", s.GetType)
		v1.GET("/emailvalidators/{id}", s.GetName)
		v1.GET("/emailvalidators/{id}", s.GetType)
		v1.GET("/emailvalidators", s.ListEmailValidator)
		v1.POST("/emailvalidators", s.CreateEmailValidator)
		v1.GET("/emailvalidators/{id}", s.GetEmailValidator)
		v1.PUT("/emailvalidators/{id}", s.UpdateEmailValidator)
		v1.DELETE("/emailvalidators/{id}", s.DeleteEmailValidator)
		v1.GET("/numericvalidators/{id}", s.GetName)
		v1.GET("/numericvalidators/{id}", s.GetType)
		v1.GET("/numericvalidators/{id}", s.GetName)
		v1.GET("/numericvalidators/{id}", s.GetType)
		v1.GET("/numericvalidators", s.ListNumericValidator)
		v1.POST("/numericvalidators", s.CreateNumericValidator)
		v1.GET("/numericvalidators/{id}", s.GetNumericValidator)
		v1.PUT("/numericvalidators/{id}", s.UpdateNumericValidator)
		v1.DELETE("/numericvalidators/{id}", s.DeleteNumericValidator)
		v1.GET("/rangevalidators/{id}", s.GetName)
		v1.GET("/rangevalidators/{id}", s.GetType)
		v1.GET("/rangevalidators/{id}", s.GetName)
		v1.GET("/rangevalidators/{id}", s.GetType)
		v1.GET("/rangevalidators", s.ListRangeValidator)
		v1.POST("/rangevalidators", s.CreateRangeValidator)
		v1.GET("/rangevalidators/{id}", s.GetRangeValidator)
		v1.PUT("/rangevalidators/{id}", s.UpdateRangeValidator)
		v1.DELETE("/rangevalidators/{id}", s.DeleteRangeValidator)
		v1.GET("/lengthvalidators/{id}", s.GetName)
		v1.GET("/lengthvalidators/{id}", s.GetType)
		v1.GET("/lengthvalidators/{id}", s.GetName)
		v1.GET("/lengthvalidators/{id}", s.GetType)
		v1.GET("/lengthvalidators", s.ListLengthValidator)
		v1.POST("/lengthvalidators", s.CreateLengthValidator)
		v1.GET("/lengthvalidators/{id}", s.GetLengthValidator)
		v1.PUT("/lengthvalidators/{id}", s.UpdateLengthValidator)
		v1.DELETE("/lengthvalidators/{id}", s.DeleteLengthValidator)
		v1.GET("/regexvalidators/{id}", s.GetName)
		v1.GET("/regexvalidators/{id}", s.GetType)
		v1.GET("/regexvalidators/{id}", s.GetName)
		v1.GET("/regexvalidators/{id}", s.GetType)
		v1.GET("/regexvalidators", s.ListRegexValidator)
		v1.POST("/regexvalidators", s.CreateRegexValidator)
		v1.GET("/regexvalidators/{id}", s.GetRegexValidator)
		v1.PUT("/regexvalidators/{id}", s.UpdateRegexValidator)
		v1.DELETE("/regexvalidators/{id}", s.DeleteRegexValidator)
		v1.GET("/enumvalidators/{id}", s.GetName)
		v1.GET("/enumvalidators/{id}", s.GetType)
		v1.GET("/enumvalidators/{id}", s.GetName)
		v1.GET("/enumvalidators/{id}", s.GetType)
		v1.GET("/enumvalidators", s.ListEnumValidator)
		v1.POST("/enumvalidators", s.CreateEnumValidator)
		v1.GET("/enumvalidators/{id}", s.GetEnumValidator)
		v1.PUT("/enumvalidators/{id}", s.UpdateEnumValidator)
		v1.DELETE("/enumvalidators/{id}", s.DeleteEnumValidator)
		v1.GET("/datevalidators/{id}", s.GetName)
		v1.GET("/datevalidators/{id}", s.GetType)
		v1.GET("/datevalidators/{id}", s.GetName)
		v1.GET("/datevalidators/{id}", s.GetType)
		v1.GET("/datevalidators", s.ListDateValidator)
		v1.POST("/datevalidators", s.CreateDateValidator)
		v1.GET("/datevalidators/{id}", s.GetDateValidator)
		v1.PUT("/datevalidators/{id}", s.UpdateDateValidator)
		v1.DELETE("/datevalidators/{id}", s.DeleteDateValidator)
		v1.GET("/uuidvalidators/{id}", s.GetName)
		v1.GET("/uuidvalidators/{id}", s.GetType)
		v1.GET("/uuidvalidators/{id}", s.GetName)
		v1.GET("/uuidvalidators/{id}", s.GetType)
		v1.GET("/uuidvalidators", s.ListUUIDValidator)
		v1.POST("/uuidvalidators", s.CreateUUIDValidator)
		v1.GET("/uuidvalidators/{id}", s.GetUUIDValidator)
		v1.PUT("/uuidvalidators/{id}", s.UpdateUUIDValidator)
		v1.DELETE("/uuidvalidators/{id}", s.DeleteUUIDValidator)
		v1.GET("/urlvalidators/{id}", s.GetName)
		v1.GET("/urlvalidators/{id}", s.GetType)
		v1.GET("/urlvalidators/{id}", s.GetName)
		v1.GET("/urlvalidators/{id}", s.GetType)
		v1.GET("/urlvalidators", s.ListURLValidator)
		v1.POST("/urlvalidators", s.CreateURLValidator)
		v1.GET("/urlvalidators/{id}", s.GetURLValidator)
		v1.PUT("/urlvalidators/{id}", s.UpdateURLValidator)
		v1.DELETE("/urlvalidators/{id}", s.DeleteURLValidator)
		v1.GET("/phonevalidators/{id}", s.GetName)
		v1.GET("/phonevalidators/{id}", s.GetType)
		v1.GET("/phonevalidators/{id}", s.GetName)
		v1.GET("/phonevalidators/{id}", s.GetType)
		v1.GET("/phonevalidators", s.ListPhoneValidator)
		v1.POST("/phonevalidators", s.CreatePhoneValidator)
		v1.GET("/phonevalidators/{id}", s.GetPhoneValidator)
		v1.PUT("/phonevalidators/{id}", s.UpdatePhoneValidator)
		v1.DELETE("/phonevalidators/{id}", s.DeletePhoneValidator)
		v1.GET("/passwordvalidators/{id}", s.GetName)
		v1.GET("/passwordvalidators/{id}", s.GetType)
		v1.GET("/passwordvalidators/{id}", s.GetName)
		v1.GET("/passwordvalidators/{id}", s.GetType)
		v1.GET("/passwordvalidators", s.ListPasswordValidator)
		v1.POST("/passwordvalidators", s.CreatePasswordValidator)
		v1.GET("/passwordvalidators/{id}", s.GetPasswordValidator)
		v1.PUT("/passwordvalidators/{id}", s.UpdatePasswordValidator)
		v1.DELETE("/passwordvalidators/{id}", s.DeletePasswordValidator)
		v1.GET("/businessidentifiervalidators/{id}", s.GetName)
		v1.GET("/businessidentifiervalidators/{id}", s.GetType)
		v1.GET("/businessidentifiervalidators/{id}", s.GetName)
		v1.GET("/businessidentifiervalidators/{id}", s.GetType)
		v1.GET("/businessidentifiervalidators", s.ListBusinessIdentifierValidator)
		v1.POST("/businessidentifiervalidators", s.CreateBusinessIdentifierValidator)
		v1.GET("/businessidentifiervalidators/{id}", s.GetBusinessIdentifierValidator)
		v1.PUT("/businessidentifiervalidators/{id}", s.UpdateBusinessIdentifierValidator)
		v1.DELETE("/businessidentifiervalidators/{id}", s.DeleteBusinessIdentifierValidator)
		v1.GET("/geolocationvalidators/{id}", s.GetName)
		v1.GET("/geolocationvalidators/{id}", s.GetType)
		v1.GET("/geolocationvalidators/{id}", s.GetName)
		v1.GET("/geolocationvalidators/{id}", s.GetType)
		v1.GET("/geolocationvalidators", s.ListGeoLocationValidator)
		v1.POST("/geolocationvalidators", s.CreateGeoLocationValidator)
		v1.GET("/geolocationvalidators/{id}", s.GetGeoLocationValidator)
		v1.PUT("/geolocationvalidators/{id}", s.UpdateGeoLocationValidator)
		v1.DELETE("/geolocationvalidators/{id}", s.DeleteGeoLocationValidator)

		v1.{{.Method|upper}}("{{.Path}}", s.{{.Function|title}})
		
	}
}

func (s *Server) healthCheck(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{
		"status":    "healthy",
		"timestamp": "auto-generated",
		"version":   "1.0.0",
	})
}

{{range .Routes}}
func (s *Server) {{.Function|title}}(c *gin.Context) {
	// Auto-generated implementation for {{.Function}}
	// TODO: Implement business logic

	{{if .Auth.Required}}
	// JWT authentication would be here
	

	c.JSON(http.StatusOK, gin.H{
		"message": "{{.Function}} endpoint auto-generated",
		"method": "{{.Method}}",
		"path": "{{.Path}}",
		"auto_generated": true,
	})
}
{{end}}

func main() {
	config := &Config{
		Port:      getEnv("PORT", "8080"),
		JWTSecret: getEnv("JWT_SECRET", "your-secret-key"),
		RedisURL:  getEnv("REDIS_URL", "localhost:6379"),
	}

	server := NewServer(config)
	log.Printf("Auto-generated API server starting on port %s", config.Port)

	if err := server.router.Run(":" + config.Port); err != nil {
		log.Fatalf("Failed to start server: %v", err)
	}
}

func getEnv(key, defaultValue string) string {
	if value := os.Getenv(key); value != "" {
		return value
	}
	return defaultValue
}